/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/u1SmWP4YTMY
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Caudex } from 'next/font/google'
import { Prata } from 'next/font/google'

caudex({
  subsets: ['latin'],
  display: 'swap',
})

prata({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@src/components/ui/button"

export function Layout() {
  return (
    <div className="flex flex-col min-h-dvh">
      <header className="sticky top-0 z-40 w-full bg-background">
        <div className="container flex items-center justify-between h-16 px-4 md:px-6">
          <Link href="#" className="flex items-center gap-2" prefetch={false}>
            <SunIcon className="w-8 h-8" />
            <span className="font-bold text-lg">Suno</span>
          </Link>
          <nav className="hidden space-x-4 md:flex">
            <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
              About
            </Link>
            <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
              Products
            </Link>
            <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
              Contact
            </Link>
            <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
              Privacy
            </Link>
          </nav>
          <Button variant="outline" size="sm" className="md:hidden">
            <MenuIcon className="w-5 h-5" />
            <span className="sr-only">Toggle menu</span>
          </Button>
        </div>
      </header>
      <main className="flex-1">
        <section className="relative w-full h-[600px] md:h-[700px] lg:h-[800px]">
          <img src="/vercel.svg" alt="Hero Image" fill className="object-cover object-center" />
          <div className="absolute inset-0 flex flex-col items-center justify-center px-4 text-center bg-black/50 text-primary-foreground">
            <h1 className="text-4xl font-bold tracking-tight sm:text-5xl md:text-6xl">Discover the Art of Fashion</h1>
            <p className="max-w-3xl mt-6 text-lg">
              Explore our curated collection of sustainable and ethically crafted clothing, designed to elevate your
              style and inspire your journey.
            </p>
            <div className="mt-10 space-x-4">
              <Link
                href="#"
                className="inline-flex items-center justify-center h-10 px-6 text-sm font-medium transition-colors rounded-md bg-primary text-primary-foreground hover:bg-primary/90 focus:outline-none focus:ring-1 focus:ring-primary focus:ring-offset-2"
                prefetch={false}
              >
                Shop Now
              </Link>
              <Link
                href="#"
                className="inline-flex items-center justify-center h-10 px-6 text-sm font-medium transition-colors rounded-md bg-transparent border border-primary text-primary hover:bg-primary hover:text-primary-foreground focus:outline-none focus:ring-1 focus:ring-primary focus:ring-offset-2"
                prefetch={false}
              >
                Learn More
              </Link>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-16 lg:py-20">
          <div className="container grid grid-cols-1 gap-8 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
            <div className="relative overflow-hidden transition-transform duration-300 ease-in-out rounded-lg shadow-lg group hover:shadow-xl hover:-translate-y-2">
              <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
                <span className="sr-only">View Product</span>
              </Link>
              <img
                src="/vercel.svg"
                alt="Product 1"
                width={500}
                height={600}
                className="object-cover w-full h-64"
                style={{ aspectRatio: "500/600", objectFit: "cover" }}
              />
              <div className="p-4 bg-background">
                <h3 className="text-xl font-bold">Sustainable Linen Dress</h3>
                <p className="text-sm text-muted-foreground">Ethically crafted, breathable linen dress.</p>
                <h4 className="text-lg font-semibold md:text-xl">$89.99</h4>
              </div>
            </div>
            <div className="relative overflow-hidden transition-transform duration-300 ease-in-out rounded-lg shadow-lg group hover:shadow-xl hover:-translate-y-2">
              <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
                <span className="sr-only">View Product</span>
              </Link>
              <img
                src="/vercel.svg"
                alt="Product 2"
                width={500}
                height={600}
                className="object-cover w-full h-64"
                style={{ aspectRatio: "500/600", objectFit: "cover" }}
              />
              <div className="p-4 bg-background">
                <h3 className="text-xl font-bold">Organic Cotton Tee</h3>
                <p className="text-sm text-muted-foreground">Soft and sustainable organic cotton t-shirt.</p>
                <h4 className="text-lg font-semibold md:text-xl">$29.99</h4>
              </div>
            </div>
            <div className="relative overflow-hidden transition-transform duration-300 ease-in-out rounded-lg shadow-lg group hover:shadow-xl hover:-translate-y-2">
              <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
                <span className="sr-only">View Product</span>
              </Link>
              <img
                src="/vercel.svg"
                alt="Product 3"
                width={500}
                height={600}
                className="object-cover w-full h-64"
                style={{ aspectRatio: "500/600", objectFit: "cover" }}
              />
              <div className="p-4 bg-background">
                <h3 className="text-xl font-bold">Recycled Denim Jacket</h3>
                <p className="text-sm text-muted-foreground">Stylish and eco-friendly denim jacket.</p>
                <h4 className="text-lg font-semibold md:text-xl">$79.99</h4>
              </div>
            </div>
            <div className="relative overflow-hidden transition-transform duration-300 ease-in-out rounded-lg shadow-lg group hover:shadow-xl hover:-translate-y-2">
              <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
                <span className="sr-only">View Product</span>
              </Link>
              <img
                src="/vercel.svg"
                alt="Product 4"
                width={500}
                height={600}
                className="object-cover w-full h-64"
                style={{ aspectRatio: "500/600", objectFit: "cover" }}
              />
              <div className="p-4 bg-background">
                <h3 className="text-xl font-bold">Bamboo Midi Skirt</h3>
                <p className="text-sm text-muted-foreground">Sustainable and comfortable bamboo skirt.</p>
                <h4 className="text-lg font-semibold md:text-xl">$49.99</h4>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-muted py-8 md:py-12">
        <div className="container grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-4">
          <div className="space-y-4">
            <h4 className="text-lg font-bold">About</h4>
            <p className="text-muted-foreground">
              Suno is a sustainable fashion brand committed to ethical production and environmental responsibility.
            </p>
            <Link
              href="#"
              className="inline-flex items-center gap-2 text-sm font-medium hover:underline"
              prefetch={false}
            >
              Learn More
              <ArrowRightIcon className="w-4 h-4" />
            </Link>
          </div>
          <div className="space-y-4">
            <h4 className="text-lg font-bold">Products</h4>
            <ul className="space-y-2">
              <li>
                <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
                  Clothing
                </Link>
              </li>
              <li>
                <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
                  Accessories
                </Link>
              </li>
              <li>
                <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
                  Home Goods
                </Link>
              </li>
            </ul>
          </div>
          <div className="space-y-4">
            <h4 className="text-lg font-bold">Contact</h4>
            <ul className="space-y-2">
              <li>
                <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
                  Email
                </Link>
              </li>
              <li>
                <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
                  Phone
                </Link>
              </li>
              <li>
                <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
                  Address
                </Link>
              </li>
            </ul>
          </div>
          <div className="space-y-4">
            <h4 className="text-lg font-bold">Legal</h4>
            <ul className="space-y-2">
              <li>
                <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
                  Privacy Policy
                </Link>
              </li>
              <li>
                <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
                  Terms of Service
                </Link>
              </li>
            </ul>
          </div>
        </div>
        <div className="container mt-8 text-center text-sm text-muted-foreground">
          &copy; 2024 Suno. All rights reserved.
        </div>
      </footer>
    </div>
  )
}

function ArrowRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  )
}


function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function SunIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="4" />
      <path d="M12 2v2" />
      <path d="M12 20v2" />
      <path d="m4.93 4.93 1.41 1.41" />
      <path d="m17.66 17.66 1.41 1.41" />
      <path d="M2 12h2" />
      <path d="M20 12h2" />
      <path d="m6.34 17.66-1.41 1.41" />
      <path d="m19.07 4.93-1.41 1.41" />
    </svg>
  )
}
